# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateCircleRingSector
                                 A QGIS plugin
 Creates sector of circle ring
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-15
        copyright            : (C) 2018 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateCircleRingSector class from file CreateCircleRingSector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .circ_ring_sector import CreateCircleRingSector
    return CreateCircleRingSector(iface)
